### PR TITLE
fix Promise.Then/Catch (introduced by 2a5ecf02-> b36fc8a5)

### PR DESCRIPTION
**Pull request by FuPeiJiang**
can you explain the purpose of this code ?
```c++
	if (callback) {
		AddRef();
		mReply = (HWND)-1;
		OnFinish();
	}
```
callback will always be null
___
is `callback->AddRef();` needed in my code ?
it's missing, but it still works ?
___
here is what I tried to run:

```ahk
Persistent 1

script:="
(
Persistent 1
inc(obj) {
    loop 1000 {
        ++obj.a
    }
}
)"

obj:={a:0}
todo_count:=4
finished_count:=0
dont_garbage_collect:=[]
thread1:=Worker(script)
loop todo_count {
    dont_garbage_collect.Push(thread1.AsyncCall("inc",obj).Then(done).Catch(failed))
}

done(result) {
    global finished_count
    ++finished_count
    if (finished_count == todo_count) {
        thread1.ExitApp()
        MsgBox obj.a
    }
}
failed(Exception) {
    MsgBox "failed"
}
```

I'm trying to achieve the same as below: <https://hotkeyit.github.io/v2/docs/commands/CriticalObject.htm>
the execution speed is really slow (I used release build) 
I can only loop 1000 times, (I don't care about looping 1000000 times though) (I would use compiled code)

```ahk
obj:=CriticalObject({a:0}) ; Create new CriticalObject
script:="
(
  obj:=CriticalObject(a_args[1]) ; get CriticalObject from pointer
  lpCS:=CriticalObject(obj,2) ; get CriticalSection
  loop 1000000
    EnterCriticalSection(lpCS),obj.a++,LeaveCriticalSection(lpCS) ; manually lock and unlock CriticalSection
)"

threads:=[]
loop 4
  threads.Push(TlsThread(script,ObjPtr(obj) "")) ; create 4 threads passing the pointer (as string!) to command line parameters
While threads[1].AhkReady() || threads[2].AhkReady() || threads[3].AhkReady() || threads[4].AhkReady() ; wait for threads to finish
  ToolTip obj.a
MsgBox obj.a ; = 4000000
```

### CODE REVIEW

**Comment by thqby** [comment]
```
p := thread1.AsyncCall("inc",obj)
Sleep(2000)
p.Then(done)
```

**Comment by FuPeiJiang** [comment]
this shouldn't be the behavior of `.Then()`, why only add a `.Then()` when the Promise has finished executing ? the whole purpose is to have a callback called when it finishes executing, and `.Then()` adds that event listener
and how do you check if it has finished executing ?

`mState` will only be non-zero when the Promise has finished executing,

**Comment by FuPeiJiang** [comment]
commit 2a5ecf0 always sets `mComplete = callback;`
commit b36fc8a always sets `mComplete` to `nullptr`, unless `mState` is non-zero (Promise has already finished executing)

**Comment by thqby** [comment]
It should not be assumed that '.Then' will be called immediately, and for some purpose you may want to add callbacks later.

> commit https://github.com/thqby/AutoHotkey_H/commit/b36fc8a524b19b8893204c189fab0559e7d63cea always sets mComplete to nullptr

Yes, this is bug.

**Comment by FuPeiJiang** [comment]
> It should not be assumed that '.Then' will be called immediately, and for some purpose you may want to add callbacks later.

with my commit, you are allowed to add callbacks before the Promise has finished, but not after, this counts as "later", but not too late

if you want to be able to add `.Then/Catch` after the Promise has finished, and have their callbacks immediately called, you can do:

```c++
	Object *callback = dynamic_cast<Object *>(TokenToObject(*aParam[0]));
	if (!callback)
		_o_throw(ERR_INVALID_FUNCTOR);
	if (mState) { //if finished
		if (mState & aID) { //if finished is the callback we are adding
			ExprTokenType* param[] = { &mResult };
			ResultToken result;
			TCHAR buf[MAX_INTEGER_LENGTH];
			mState |= 4;
			result.InitResult(buf);
			callback->Invoke(result, IT_CALL, nullptr, ExprTokenType(callback), param, 1);
			result.Free();
		}
		_o_return(this);
		return;
	}
```

**Comment by thqby** [comment]
fixed by 9c58d3d5a6f75581217b90b90a148a6d0392fc3b

**Pull request closed without merging**
